site_name: Digital Casting System
site_author: Wei-Ting Chen

nav:
  - Getting Started: index.md
  - User Guide: installation.md
  - API Reference: api.md
  - About: about.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

copyright: Copyright &copy; 2024 <a href="https://github.com/USI-FMAA">USI FMAA</a>, Maintained by the <a href="https://github.com/WeiTing1991">Wei-Ting Chen</a>.
