name: Build

on:
  push:
    branches:
      - master
      - main

jobs:
  build_main:
    runs-on: ubuntu-latest
    env:
      PROJECT_ROOT: ${{ github.workspace}}

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project and python dependencies
        run: |
          uv sync --all-extras --dev

