name: Doc build and deploy

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      PROJECT_ROOT: ${{ github.workspace}}

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # - name: Checkout submodule branch
      #   run: |
      #     cd external_controllers || exit 1
      #     git checkout main

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project and python dependencies
        run: |
          uv sync --all-extras --dev

      - name: Build Docs
        run: |
          ${{ github.workspace }}/.venv/bin/python -m mkdocs build

      - name: Deploy Docs to GitHub Pages
        run: |
          ${{ github.workspace }}/.venv/bin/python -m mkdocs gh-deploy --force

#   - uses: actions/cache@v4
#     with:
#       key: mkdocs-material-${{ env.cache_id }}
#       path: .cache
#       restore-keys: |
#         mkdocs-material-
#
#   - name: Install Mkdocs
#     run: pip install mkdocs-material
#
#
#
#
#   - uses: actions/setup-python@v5
#     with:
#       python-version: 3.x
#   - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
#
